<?php

namespace Database\Seeders;

use App\Models\Resident;
use App\Models\User;
use Illuminate\Database\Seeder;

class ResidentSeeder extends Seeder
{
    public function run(): void
    {
        $createdBy = User::role('system_admin')->first()?->id;

        $residents = [
            [
                'first_name' => 'Margaret',
                'last_name' => 'Thompson',
                'date_of_birth' => '1940-03-15',
                'gender' => 'female',
                'admission_date' => '2024-06-10',
                'room_number' => '101',
                'bed_number' => 'A',
                'status' => 'active',
                'blood_type' => 'A+',
                'allergies' => 'Penicillin, Latex',
                'medical_conditions' => 'Type 2 Diabetes, Mild Dementia',
                'mobility_status' => 'assisted',
                'dietary_requirements' => 'Low sugar, diabetic-friendly meals',
                'fall_risk_level' => 'medium',
                'dnr_status' => false,
                'emergency_contact_name' => 'David Thompson',
                'emergency_contact_phone' => '+254 712 345 678',
                'emergency_contact_relationship' => 'Son',
                'nok_name' => 'David Thompson',
                'nok_phone' => '+254 712 345 678',
                'nok_email' => 'david.thompson@email.com',
                'nok_relationship' => 'Son',
                'nok_address' => '45 Riverside Drive, Nairobi',
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Omondi',
                'date_of_birth' => '1935-11-22',
                'gender' => 'male',
                'admission_date' => '2024-01-15',
                'room_number' => '102',
                'bed_number' => 'A',
                'status' => 'active',
                'blood_type' => 'O+',
                'allergies' => 'Sulfa drugs',
                'medical_conditions' => 'Hypertension, Arthritis, Chronic Back Pain',
                'mobility_status' => 'wheelchair',
                'dietary_requirements' => 'Low sodium diet',
                'fall_risk_level' => 'high',
                'dnr_status' => true,
                'emergency_contact_name' => 'Grace Omondi',
                'emergency_contact_phone' => '+254 723 456 789',
                'emergency_contact_relationship' => 'Wife',
                'nok_name' => 'Grace Omondi',
                'nok_phone' => '+254 723 456 789',
                'nok_email' => 'grace.omondi@email.com',
                'nok_relationship' => 'Wife',
                'nok_address' => '12 Westlands Road, Nairobi',
            ],
            [
                'first_name' => 'Florence',
                'last_name' => 'Wanjiku',
                'date_of_birth' => '1942-07-08',
                'gender' => 'female',
                'admission_date' => '2024-09-01',
                'room_number' => '103',
                'bed_number' => 'A',
                'status' => 'active',
                'blood_type' => 'B+',
                'medical_conditions' => 'Osteoporosis, Mild Anxiety',
                'mobility_status' => 'assisted',
                'fall_risk_level' => 'medium',
                'dnr_status' => false,
                'emergency_contact_name' => 'Peter Wanjiku',
                'emergency_contact_phone' => '+254 734 567 890',
                'emergency_contact_relationship' => 'Son',
            ],
            [
                'first_name' => 'Robert',
                'last_name' => 'Kimani',
                'date_of_birth' => '1938-02-28',
                'gender' => 'male',
                'admission_date' => '2023-11-20',
                'room_number' => '104',
                'bed_number' => 'A',
                'status' => 'active',
                'blood_type' => 'AB+',
                'allergies' => 'Aspirin',
                'medical_conditions' => 'Parkinson\'s Disease, COPD',
                'mobility_status' => 'wheelchair',
                'dietary_requirements' => 'Soft foods, pureed meals',
                'fall_risk_level' => 'high',
                'dnr_status' => true,
                'emergency_contact_name' => 'Susan Kimani',
                'emergency_contact_phone' => '+254 745 678 901',
                'emergency_contact_relationship' => 'Daughter',
                'nok_name' => 'Susan Kimani',
                'nok_phone' => '+254 745 678 901',
                'nok_email' => 'susan.kimani@email.com',
                'nok_relationship' => 'Daughter',
                'nok_address' => '78 Karen Road, Nairobi',
            ],
            [
                'first_name' => 'Elizabeth',
                'last_name' => 'Muthoni',
                'date_of_birth' => '1945-05-12',
                'gender' => 'female',
                'admission_date' => '2025-01-05',
                'room_number' => '105',
                'bed_number' => 'A',
                'status' => 'active',
                'blood_type' => 'O-',
                'medical_conditions' => 'Heart Failure (managed), Depression',
                'mobility_status' => 'independent',
                'dietary_requirements' => 'Heart-healthy, low fat',
                'fall_risk_level' => 'low',
                'dnr_status' => false,
                'emergency_contact_name' => 'John Muthoni',
                'emergency_contact_phone' => '+254 756 789 012',
                'emergency_contact_relationship' => 'Husband',
            ],
            [
                'first_name' => 'William',
                'last_name' => 'Njoroge',
                'date_of_birth' => '1930-09-18',
                'gender' => 'male',
                'admission_date' => '2023-06-12',
                'room_number' => '106',
                'bed_number' => 'A',
                'status' => 'active',
                'blood_type' => 'A-',
                'allergies' => 'Morphine, Codeine',
                'medical_conditions' => 'Advanced Dementia, Diabetes Type 1',
                'mobility_status' => 'bedridden',
                'dietary_requirements' => 'Tube feeding, nutritional supplements',
                'fall_risk_level' => 'low',
                'dnr_status' => true,
                'emergency_contact_name' => 'Alice Njoroge',
                'emergency_contact_phone' => '+254 767 890 123',
                'emergency_contact_relationship' => 'Daughter',
                'nok_name' => 'Alice Njoroge',
                'nok_phone' => '+254 767 890 123',
                'nok_email' => 'alice.njoroge@email.com',
                'nok_relationship' => 'Daughter',
                'nok_address' => '34 Thika Road, Nairobi',
            ],
            [
                'first_name' => 'Mary',
                'last_name' => 'Akinyi',
                'date_of_birth' => '1948-12-03',
                'gender' => 'female',
                'admission_date' => '2025-03-15',
                'room_number' => '107',
                'bed_number' => 'A',
                'status' => 'active',
                'blood_type' => 'B-',
                'medical_conditions' => 'Rheumatoid Arthritis',
                'mobility_status' => 'assisted',
                'fall_risk_level' => 'medium',
                'dnr_status' => false,
                'emergency_contact_name' => 'Joseph Akinyi',
                'emergency_contact_phone' => '+254 778 901 234',
                'emergency_contact_relationship' => 'Son',
            ],
            [
                'first_name' => 'Charles',
                'last_name' => 'Otieno',
                'date_of_birth' => '1937-04-25',
                'gender' => 'male',
                'admission_date' => '2024-08-20',
                'room_number' => '108',
                'bed_number' => 'A',
                'status' => 'active',
                'blood_type' => 'O+',
                'allergies' => 'Ibuprofen',
                'medical_conditions' => 'Stroke (2023), Hypertension',
                'mobility_status' => 'wheelchair',
                'dietary_requirements' => 'Pureed meals, thickened liquids',
                'fall_risk_level' => 'high',
                'dnr_status' => false,
                'emergency_contact_name' => 'Jane Otieno',
                'emergency_contact_phone' => '+254 789 012 345',
                'emergency_contact_relationship' => 'Wife',
                'nok_name' => 'Jane Otieno',
                'nok_phone' => '+254 789 012 345',
                'nok_email' => 'jane.otieno@email.com',
                'nok_relationship' => 'Wife',
                'nok_address' => '56 Mombasa Road, Nairobi',
            ],
            [
                'first_name' => 'Agnes',
                'last_name' => 'Chebet',
                'date_of_birth' => '1943-08-14',
                'gender' => 'female',
                'admission_date' => '2025-06-01',
                'room_number' => '109',
                'bed_number' => 'A',
                'status' => 'active',
                'medical_conditions' => 'Mild Cognitive Impairment',
                'mobility_status' => 'independent',
                'fall_risk_level' => 'low',
                'dnr_status' => false,
                'emergency_contact_name' => 'Daniel Chebet',
                'emergency_contact_phone' => '+254 790 123 456',
                'emergency_contact_relationship' => 'Son',
            ],
            [
                'first_name' => 'Samuel',
                'last_name' => 'Mwangi',
                'date_of_birth' => '1939-01-30',
                'gender' => 'male',
                'admission_date' => '2024-04-10',
                'room_number' => '110',
                'bed_number' => 'A',
                'status' => 'active',
                'blood_type' => 'AB-',
                'medical_conditions' => 'Chronic Kidney Disease, Anemia',
                'mobility_status' => 'assisted',
                'dietary_requirements' => 'Renal diet, low potassium',
                'fall_risk_level' => 'medium',
                'dnr_status' => false,
                'emergency_contact_name' => 'Rachel Mwangi',
                'emergency_contact_phone' => '+254 701 234 567',
                'emergency_contact_relationship' => 'Daughter',
                'nok_name' => 'Rachel Mwangi',
                'nok_phone' => '+254 701 234 567',
                'nok_email' => 'rachel.mwangi@email.com',
                'nok_relationship' => 'Daughter',
                'nok_address' => '90 Ngong Road, Nairobi',
            ],
            [
                'first_name' => 'Dorothy',
                'last_name' => 'Kamau',
                'date_of_birth' => '1946-10-07',
                'gender' => 'female',
                'admission_date' => '2024-02-14',
                'discharge_date' => '2025-08-30',
                'room_number' => '111',
                'bed_number' => 'A',
                'status' => 'discharged',
                'medical_conditions' => 'Hip Replacement Recovery',
                'mobility_status' => 'independent',
                'fall_risk_level' => 'low',
                'dnr_status' => false,
                'notes' => 'Discharged to family home after successful rehabilitation. Follow-up care plan in place.',
                'emergency_contact_name' => 'Michael Kamau',
                'emergency_contact_phone' => '+254 712 567 890',
                'emergency_contact_relationship' => 'Son',
            ],
            [
                'first_name' => 'Peter',
                'last_name' => 'Wafula',
                'date_of_birth' => '1941-06-19',
                'gender' => 'male',
                'admission_date' => '2025-07-01',
                'room_number' => '112',
                'bed_number' => 'A',
                'status' => 'on_leave',
                'blood_type' => 'A+',
                'medical_conditions' => 'Moderate Dementia, Diabetes Type 2',
                'mobility_status' => 'assisted',
                'fall_risk_level' => 'medium',
                'dnr_status' => false,
                'notes' => 'On family visit until January 15, 2026.',
                'emergency_contact_name' => 'Martha Wafula',
                'emergency_contact_phone' => '+254 723 678 901',
                'emergency_contact_relationship' => 'Wife',
                'nok_name' => 'Martha Wafula',
                'nok_phone' => '+254 723 678 901',
                'nok_email' => 'martha.wafula@email.com',
                'nok_relationship' => 'Wife',
                'nok_address' => '23 Kisumu Road, Nairobi',
            ],
        ];

        foreach ($residents as $resident) {
            Resident::firstOrCreate(
                ['first_name' => $resident['first_name'], 'last_name' => $resident['last_name']],
                array_merge($resident, ['created_by' => $createdBy])
            );
        }
    }
}
